package cz.lipovcan.buybread;

/**
 * This class was automatically generated by the data modeler tool.
 */

public class cv_form implements java.io.Serializable {

    static final long serialVersionUID = 1L;

    public cv_form() {
    }




}