package cz.lipovcan.buybread;

import java.math.BigInteger;

/**
 * This class was automatically generated by the data modeler tool.
 */

@javax.persistence.Entity
public class Inventory implements java.io.Serializable {

	static final long serialVersionUID = 1L;

	@javax.persistence.GeneratedValue(generator = "INVENTORY_ID_GENERATOR", strategy = javax.persistence.GenerationType.AUTO)
	@javax.persistence.Id
	@javax.persistence.SequenceGenerator(sequenceName = "INVENTORY_ID_SEQ", name = "INVENTORY_ID_GENERATOR")
	private java.lang.Long id;

	@org.kie.api.definition.type.Label("Product name")
	private java.lang.String name;

	@org.kie.api.definition.type.Label("Amount of exact product")
	private java.lang.Integer amount;

	@org.kie.api.definition.type.Label(value = "daysToExpire")
	private java.lang.Integer daysToExpire;

	public Inventory() {
	}

	public java.lang.Long getId() {
		return this.id;
	}

	public void setId(java.lang.Long id) {
		this.id = id;
	}

	public java.lang.String getName() {
		return this.name;
	}

	public void setName(java.lang.String name) {
		this.name = name;
	}

	public java.lang.Integer getAmount() {
		return this.amount;
	}

	public void setAmount(java.lang.Integer amount) {
		this.amount = amount;
	}

	public java.lang.Integer getDaysToExpire() {
		return this.daysToExpire;
	}

	public void setDaysToExpire(java.lang.Integer daysToExpire) {
		this.daysToExpire = daysToExpire;
	}

	public Inventory(java.lang.Long id, java.lang.String name,
			java.lang.Integer amount, java.lang.Integer daysToExpire) {
		this.id = id;
		this.name = name;
		this.amount = amount;
		this.daysToExpire = daysToExpire;
	}

}