package cz.lipovcan.buybread;

/**
 * This class was automatically generated by the data modeler tool.
 */

public class order_for_supplier implements java.io.Serializable {

    static final long serialVersionUID = 1L;

    public order_for_supplier() {
    }




}