package cz.lipovcan.buybread;

/**
 * This class was automatically generated by the data modeler tool.
 */

@javax.persistence.Entity
@javax.xml.bind.annotation.XmlRootElement
public class Product implements java.io.Serializable {

	static final long serialVersionUID = 1L;

	@javax.persistence.GeneratedValue(strategy = javax.persistence.GenerationType.AUTO, generator = "PRODUCT_ID_GENERATOR")
	@javax.persistence.Id
	@javax.persistence.SequenceGenerator(sequenceName = "PRODUCT_ID_SEQ", name = "PRODUCT_ID_GENERATOR")
	private java.lang.Long id;

	private float product_price;

	private java.lang.String product_name;

	private int product_amount;

	private java.lang.String supplier_name;

	private java.lang.String database_stats;

	private java.lang.Integer actual_contract_amount;

	public Product() {
	}

	public java.lang.Long getId() {
		return this.id;
	}

	public void setId(java.lang.Long id) {
		this.id = id;
	}

	public float getProduct_price() {
		return this.product_price;
	}

	public void setProduct_price(float product_price) {
		this.product_price = product_price;
	}

	public java.lang.String getProduct_name() {
		return this.product_name;
	}

	public void setProduct_name(java.lang.String product_name) {
		this.product_name = product_name;
	}

	public int getProduct_amount() {
		return this.product_amount;
	}

	public void setProduct_amount(int product_amount) {
		this.product_amount = product_amount;
	}

	public java.lang.String getSupplier_name() {
		return this.supplier_name;
	}

	public void setSupplier_name(java.lang.String supplier_name) {
		this.supplier_name = supplier_name;
	}

	public java.lang.String getDatabase_stats() {
		return this.database_stats;
	}

	public void setDatabase_stats(java.lang.String database_stats) {
		this.database_stats = database_stats;
	}

	public java.lang.Integer getActual_contract_amount() {
		return this.actual_contract_amount;
	}

	public void setActual_contract_amount(
			java.lang.Integer actual_contract_amount) {
		this.actual_contract_amount = actual_contract_amount;
	}

	public Product(java.lang.Long id, float product_price,
			java.lang.String product_name, int product_amount,
			java.lang.String supplier_name, java.lang.String database_stats,
			java.lang.Integer actual_contract_amount) {
		this.id = id;
		this.product_price = product_price;
		this.product_name = product_name;
		this.product_amount = product_amount;
		this.supplier_name = supplier_name;
		this.database_stats = database_stats;
		this.actual_contract_amount = actual_contract_amount;
	}

}