package cz.lipovcan.buybread;

/**
 * This class was automatically generated by the data modeler tool.
 */

@javax.persistence.Entity
@javax.xml.bind.annotation.XmlRootElement
public class Product implements java.io.Serializable {

	static final long serialVersionUID = 1L;

	@javax.persistence.GeneratedValue(strategy = javax.persistence.GenerationType.AUTO, generator = "PRODUCT_ID_GENERATOR")
	@javax.persistence.Id
	@javax.persistence.SequenceGenerator(sequenceName = "PRODUCT_ID_SEQ", name = "PRODUCT_ID_GENERATOR")
	private java.lang.Long id;

	private float product_price;

	private java.lang.String product_name;

	private int product_amount;

	private java.lang.String product_stats;

	private java.lang.String product_supplier;

	public Product() {
	}

	public java.lang.Long getId() {
		return this.id;
	}

	public void setId(java.lang.Long id) {
		this.id = id;
	}

	public float getProduct_price() {
		return this.product_price;
	}

	public void setProduct_price(float product_price) {
		this.product_price = product_price;
	}

	public java.lang.String getProduct_name() {
		return this.product_name;
	}

	public void setProduct_name(java.lang.String product_name) {
		this.product_name = product_name;
	}

	public int getProduct_amount() {
		return this.product_amount;
	}

	public void setProduct_amount(int product_amount) {
		this.product_amount = product_amount;
	}

	public java.lang.String getProduct_stats() {
		return this.product_stats;
	}

	public void setProduct_stats(java.lang.String product_stats) {
		this.product_stats = product_stats;
	}

	public java.lang.String getProduct_supplier() {
		return this.product_supplier;
	}

	public void setProduct_supplier(java.lang.String product_supplier) {
		this.product_supplier = product_supplier;
	}

	public Product(java.lang.Long id, float product_price,
			java.lang.String product_name, int product_amount,
			java.lang.String product_stats, java.lang.String product_supplier) {
		this.id = id;
		this.product_price = product_price;
		this.product_name = product_name;
		this.product_amount = product_amount;
		this.product_stats = product_stats;
		this.product_supplier = product_supplier;
	}

}