package cz.lipovcan.buybread;

/**
 * This class was automatically generated by the data modeler tool.
 */

@javax.persistence.Entity
public class Product implements java.io.Serializable {

	static final long serialVersionUID = 1L;

	@javax.persistence.GeneratedValue(strategy = javax.persistence.GenerationType.AUTO, generator = "PRODUCT_ID_GENERATOR")
	@javax.persistence.Id
	@javax.persistence.SequenceGenerator(sequenceName = "PRODUCT_ID_SEQ", name = "PRODUCT_ID_GENERATOR")
	private java.lang.Long id;

	private java.lang.String name;

	private int amount;

	private float product_price;

	public Product() {
	}

	public java.lang.Long getId() {
		return this.id;
	}

	public void setId(java.lang.Long id) {
		this.id = id;
	}

	public java.lang.String getName() {
		return this.name;
	}

	public void setName(java.lang.String name) {
		this.name = name;
	}

	public int getAmount() {
		return this.amount;
	}

	public void setAmount(int amount) {
		this.amount = amount;
	}

	public float getProduct_price() {
		return this.product_price;
	}

	public void setProduct_price(float product_price) {
		this.product_price = product_price;
	}

	public Product(java.lang.Long id, java.lang.String name, int amount,
			float product_price) {
		this.id = id;
		this.name = name;
		this.amount = amount;
		this.product_price = product_price;
	}

}