package cz.lipovcan.buybread;

/**
 * This class was automatically generated by the data modeler tool.
 */

@javax.persistence.Entity
public class Supplier_contract implements java.io.Serializable {

	static final long serialVersionUID = 1L;

	@javax.persistence.GeneratedValue(strategy = javax.persistence.GenerationType.AUTO, generator = "SUPPLIER_CONTRACT_ID_GENERATOR")
	@javax.persistence.Id
	@javax.persistence.SequenceGenerator(sequenceName = "SUPPLIER_CONTRACT_ID_SEQ", name = "SUPPLIER_CONTRACT_ID_GENERATOR")
	private java.lang.Long id;

	@javax.persistence.OneToMany(fetch = javax.persistence.FetchType.EAGER, cascade = {javax.persistence.CascadeType.ALL})
	private java.util.List<cz.lipovcan.buybread.Product> products;

	@javax.persistence.ManyToOne(fetch = javax.persistence.FetchType.EAGER, cascade = {javax.persistence.CascadeType.ALL})
	private cz.lipovcan.buybread.Supplier supplier;

	private java.lang.String status;

	public Supplier_contract() {
	}

	public java.lang.Long getId() {
		return this.id;
	}

	public void setId(java.lang.Long id) {
		this.id = id;
	}

	public java.util.List<cz.lipovcan.buybread.Product> getProducts() {
		return this.products;
	}

	public void setProducts(
			java.util.List<cz.lipovcan.buybread.Product> products) {
		this.products = products;
	}

	public cz.lipovcan.buybread.Supplier getSupplier() {
		return this.supplier;
	}

	public void setSupplier(cz.lipovcan.buybread.Supplier supplier) {
		this.supplier = supplier;
	}

	public java.lang.String getStatus() {
		return this.status;
	}

	public void setStatus(java.lang.String status) {
		this.status = status;
	}

	public Supplier_contract(java.lang.Long id,
			java.util.List<cz.lipovcan.buybread.Product> products,
			cz.lipovcan.buybread.Supplier supplier, java.lang.String status) {
		this.id = id;
		this.products = products;
		this.supplier = supplier;
		this.status = status;
	}

}