package cz.lipovcan.buybread;

/**
 * This class was automatically generated by the data modeler tool.
 */

@javax.persistence.Entity
public class Supplier_contract implements java.io.Serializable {

	static final long serialVersionUID = 1L;

	@javax.persistence.GeneratedValue(strategy = javax.persistence.GenerationType.AUTO, generator = "SUPPLIER_CONTRACT_ID_GENERATOR")
	@javax.persistence.Id
	@javax.persistence.SequenceGenerator(sequenceName = "SUPPLIER_CONTRACT_ID_SEQ", name = "SUPPLIER_CONTRACT_ID_GENERATOR")
	private java.lang.Long id;

	@javax.persistence.ManyToOne(fetch = javax.persistence.FetchType.EAGER, cascade = {javax.persistence.CascadeType.ALL})
	private cz.lipovcan.buybread.Supplier supplier;

	@javax.persistence.OneToMany(fetch = javax.persistence.FetchType.EAGER, cascade = {javax.persistence.CascadeType.ALL})
	private java.util.List<cz.lipovcan.buybread.Product> product;

	private java.lang.Integer new_amount;

	public Supplier_contract() {
	}

	public java.lang.Long getId() {
		return this.id;
	}

	public void setId(java.lang.Long id) {
		this.id = id;
	}

	public cz.lipovcan.buybread.Supplier getSupplier() {
		return this.supplier;
	}

	public void setSupplier(cz.lipovcan.buybread.Supplier supplier) {
		this.supplier = supplier;
	}

	public java.util.List<cz.lipovcan.buybread.Product> getProduct() {
		return this.product;
	}

	public void setProduct(java.util.List<cz.lipovcan.buybread.Product> product) {
		this.product = product;
	}

	public java.lang.Integer getNew_amount() {
		return this.new_amount;
	}

	public void setNew_amount(java.lang.Integer new_amount) {
		this.new_amount = new_amount;
	}

	public Supplier_contract(java.lang.Long id,
			cz.lipovcan.buybread.Supplier supplier,
			java.util.List<cz.lipovcan.buybread.Product> product,
			java.lang.Integer new_amount) {
		this.id = id;
		this.supplier = supplier;
		this.product = product;
		this.new_amount = new_amount;
	}

}