package cz.lipovcan.buybread;

/**
 * This class was automatically generated by the data modeler tool.
 */

@javax.persistence.Entity
public class Warehouse_Database implements java.io.Serializable {

	static final long serialVersionUID = 1L;

	@javax.persistence.GeneratedValue(strategy = javax.persistence.GenerationType.AUTO, generator = "WAREHOUSE_DATABASE_ID_GENERATOR")
	@javax.persistence.Id
	@javax.persistence.SequenceGenerator(sequenceName = "WAREHOUSE_DATABASE_ID_SEQ", name = "WAREHOUSE_DATABASE_ID_GENERATOR")
	private java.lang.Long id;

	private java.lang.Integer amount;

	@org.kie.api.definition.type.Description(value = "statistics about the product. Used in Optimize_supply_chain to decide whether to order less, more or the same amount of goods.")
	private java.lang.String product_stats;

	public Warehouse_Database() {
	}

	public java.lang.Long getId() {
		return this.id;
	}

	public void setId(java.lang.Long id) {
		this.id = id;
	}

	public java.lang.Integer getAmount() {
		return this.amount;
	}

	public void setAmount(java.lang.Integer amount) {
		this.amount = amount;
	}

	public java.lang.String getProduct_stats() {
		return this.product_stats;
	}

	public void setProduct_stats(java.lang.String product_stats) {
		this.product_stats = product_stats;
	}

	public Warehouse_Database(java.lang.Long id, java.lang.Integer amount,
			java.lang.String product_stats) {
		this.id = id;
		this.amount = amount;
		this.product_stats = product_stats;
	}

}